# Generated by Django 5.2.8 on 2025-11-21 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='expense_photos/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото расхода',
                'verbose_name_plural': 'Фото расходов',
            },
        ),
        migrations.CreateModel(
            name='FoundationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фонда')),
                ('description', models.TextField(verbose_name='Описание фонда')),
                ('mission', models.TextField(verbose_name='Миссия фонда')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('bank_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('corr_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('logo', models.ImageField(upload_to='foundation/', verbose_name='Логотип')),
                ('qr_code', models.ImageField(upload_to='foundation/', verbose_name='QR код для оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информация о фонде',
                'verbose_name_plural': 'Информация о фонде',
            },
        ),
        migrations.CreateModel(
            name='FundraisingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название цели')),
                ('description', models.TextField(verbose_name='Описание цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собранная сумма')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goals/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('active', 'Активный сбор'), ('completed', 'Сбор завершен'), ('suspended', 'Сбор приостановлен')], default='active', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок сбора')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Приоритет отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Цель сбора',
                'verbose_name_plural': 'Цели сбора',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('content', models.TextField(verbose_name='Содержание новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('description', models.TextField(verbose_name='Описание расходов')),
                ('report_type', models.CharField(choices=[('purchase', 'Закупка товаров'), ('logistics', 'Логистика'), ('humanitarian', 'Гуманитарная помощь'), ('other', 'Прочие расходы')], max_length=20, verbose_name='Тип отчета')),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потраченная сумма')),
                ('document', models.FileField(blank=True, null=True, upload_to='expense_docs/', verbose_name='Документ')),
                ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отчета')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photos', models.ManyToManyField(blank=True, to='main.expensephoto', verbose_name='Фотографии')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fundraisinggoal', verbose_name='Цель сбора')),
            ],
            options={
                'verbose_name': 'Отчет о расходах',
                'verbose_name_plural': 'Отчеты о расходах',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=255, verbose_name='Имя жертвователя')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email жертвователя')),
                ('donor_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон жертвователя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пожертвования')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение от жертвователя')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Банковский перевод'), ('qr_code', 'QR код'), ('card', 'Карта'), ('cash', 'Наличные')], max_length=20, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('completed', 'Завершено'), ('failed', 'Не удалось'), ('refunded', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимное пожертвование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fundraisinggoal', verbose_name='Цель сбора')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
                'ordering': ['-created_at'],
            },
        ),
    ]
